-- This used to be hard coded
-- but I'd rather just have this here to be honest.

PROJECTILE_SPRITE_BLUE              = 0;
PROJECTILE_SPRITE_BLUE_STROBING     = 1;
PROJECTILE_SPRITE_BLUE_ELECTRIC     = 2;

PROJECTILE_SPRITE_RED               = 3;
PROJECTILE_SPRITE_RED_STROBING      = 4;
PROJECTILE_SPRITE_RED_ELECTRIC      = 5;

PROJECTILE_SPRITE_NEGATIVE          = 6;
PROJECTILE_SPRITE_NEGATIVE_STROBING = 7;
PROJECTILE_SPRITE_NEGATIVE_ELECTRIC = 8;

PROJECTILE_SPRITE_HOT_PINK          = 9;
PROJECTILE_SPRITE_HOT_PINK_STROBING = 10;
PROJECTILE_SPRITE_HOT_PINK_ELECTRIC = 11;

PROJECTILE_SPRITE_GREEN          = 12;
PROJECTILE_SPRITE_GREEN_STROBING = 13;
PROJECTILE_SPRITE_GREEN_ELECTRIC = 14;

PROJECTILE_SPRITE_BLUE_DISK      = 15;
PROJECTILE_SPRITE_RED_DISK       = 16;
PROJECTILE_SPRITE_HOT_PINK_DISK  = 17;
PROJECTILE_SPRITE_NEGATIVE_DISK  = 18;
PROJECTILE_SPRITE_GREEN_DISK     = 19;

PROJECTILE_SPRITE_PURPLE           = 20;
PROJECTILE_SPRITE_PURPLE_STROBING  = 21;
PROJECTILE_SPRITE_PURPLE_ELECTRIC  = 22;
PROJECTILE_SPRITE_PURPLE_DISK      = 23;

PROJECTILE_SPRITE_WRM           = 24;
PROJECTILE_SPRITE_WRM_STROBING  = 25;
PROJECTILE_SPRITE_WRM_ELECTRIC  = 26;
PROJECTILE_SPRITE_WRM_DISK      = 27;

PROJECTILE_SPRITE_CAUSTIC           = 28;
PROJECTILE_SPRITE_CAUSTIC_STROBING  = 29;
PROJECTILE_SPRITE_CAUSTIC_ELECTRIC  = 30;
PROJECTILE_SPRITE_CAUSTIC_DISK      = 31;

-- NOTE: this sprite has... different requirements when
-- being used as a projectile since it's "very" small in it's sprite sheet
-- probably make it 1/4th the size of other projectiles (or like 2px in game terms.)
PROJECTILE_SPRITE_SPARKLING_STAR = 20;

-- NOTE(jerry): any other sprite id higher than this is usable by custom sprites.
-- these are just the ones the game provides.

BULLET_SOURCE_NEUTRAL = 0;
BULLET_SOURCE_PLAYER  = 1;
BULLET_SOURCE_ENEMY   = 2;

LASER_HAZARD_DIRECTION_HORIZONTAL = 0;
LASER_HAZARD_DIRECTION_VERTICAL = 1;

PLAY_AREA_EDGE_BLOCKING    = 0;
PLAY_AREA_EDGE_DEADLY      = 1;
PLAY_AREA_EDGE_WRAPPING    = 2;
PLAY_AREA_EDGE_PASSTHROUGH = 3;

PLAY_AREA_EDGE_TOP = 0;
PLAY_AREA_EDGE_BOTTOM    = 1;
PLAY_AREA_EDGE_LEFT    = 2;
PLAY_AREA_EDGE_RIGHT      = 3;

-- ENTITY SPRITES (based on base:manifest.lua)
ENTITY_SPRITE_SKULL_A = 0;
ENTITY_SPRITE_SKULL_B = 1;
ENTITY_SPRITE_SKULL_A1 = 2;
ENTITY_SPRITE_SKULL_B1 = 3;
ENTITY_SPRITE_BAT_A = 4;
ENTITY_SPRITE_BAT_B = 5;
ENTITY_SPRITE_BAT_B1 = 6;

-- Play Area Constants.
PLAY_AREA_EDGE_TOP = 0;
PLAY_AREA_EDGE_BOTTOM = 1;
PLAY_AREA_EDGE_LEFT = 2;
PLAY_AREA_EDGE_RIGHT = 3;

PLAY_AREA_EDGE_BLOCKING = 0;
PLAY_AREA_EDGE_DEADLY = 1;
PLAY_AREA_EDGE_WRAPPING = 2;
PLAY_AREA_EDGE_PASSTHROUGH = 3;

DIFFICULTY_NORMAL  = 0;
DIFFICULTY_EASY    = 1;
DIFFICULTY_HARD    = 2;
DIFFICULTY_HARDEST = 3;

BORDER_FLASH_ID_TYPE_NONE        = 0;
BORDER_FLASH_ID_TYPE_BLOCKING    = 1;
BORDER_FLASH_ID_TYPE_DEADLY      = 2;
BORDER_FLASH_ID_TYPE_WRAPPING    = 3;
BORDER_FLASH_ID_TYPE_PASSTHROUGH = 4;
BORDER_FLASH_ID_TYPE_ALERT       = 5;

V2_DOWN = v2(0, 1);
V2_UP = v2(0, -1);
V2_LEFT = v2(-1, 0);
V2_RIGHT = v2(1, 0);

SCRIPTABLE_RENDER_OBJECT_LAYER_BACKGROUND = 0;
SCRIPTABLE_RENDER_OBJECT_LAYER_FOREGROUND = 1;
