-- This used to be hard coded
-- but I'd rather just have this here to be honest.

PROJECTILE_SPRITE_BLUE              = 0;
PROJECTILE_SPRITE_BLUE_STROBING     = 1;
PROJECTILE_SPRITE_BLUE_ELECTRIC     = 2;

PROJECTILE_SPRITE_RED               = 3;
PROJECTILE_SPRITE_RED_STROBING      = 4;
PROJECTILE_SPRITE_RED_ELECTRIC      = 5;

PROJECTILE_SPRITE_NEGATIVE          = 6;
PROJECTILE_SPRITE_NEGATIVE_STROBING = 7;
PROJECTILE_SPRITE_NEGATIVE_ELECTRIC = 8;

PROJECTILE_SPRITE_HOT_PINK          = 9;
PROJECTILE_SPRITE_HOT_PINK_STROBING = 10;
PROJECTILE_SPRITE_HOT_PINK_ELECTRIC = 11;

PROJECTILE_SPRITE_GREEN          = 12;
PROJECTILE_SPRITE_GREEN_STROBING = 13;
PROJECTILE_SPRITE_GREEN_ELECTRIC = 14;

PROJECTILE_SPRITE_BLUE_DISK      = 15;
PROJECTILE_SPRITE_RED_DISK       = 16;
PROJECTILE_SPRITE_HOT_PINK_DISK  = 17;
PROJECTILE_SPRITE_NEGATIVE_DISK  = 18;
PROJECTILE_SPRITE_GREEN_DISK     = 19;

BULLET_SOURCE_NEUTRAL = 0;
BULLET_SOURCE_PLAYER  = 1;
BULLET_SOURCE_ENEMY   = 2;

LASER_HAZARD_DIRECTION_HORIZONTAL = 0;
LASER_HAZARD_DIRECTION_VERTICAL = 1;

PLAY_AREA_EDGE_BLOCKING    = 0;
PLAY_AREA_EDGE_DEADLY      = 1;
PLAY_AREA_EDGE_WRAPPING    = 2;
PLAY_AREA_EDGE_PASSTHROUGH = 3;

PLAY_AREA_EDGE_TOP = 0;
PLAY_AREA_EDGE_BOTTOM    = 1;
PLAY_AREA_EDGE_LEFT    = 2;
PLAY_AREA_EDGE_RIGHT      = 3;
