// Autogenerated file. Do not touch
void bind_core_lualib(lua_State* L){
    lua_register(L, "t_wait", GAME_LUA_BINDING_NAME(t_wait));
    lua_register(L, "t_fwait", GAME_LUA_BINDING_NAME(t_fwait));
    lua_register(L, "t_yield", GAME_LUA_BINDING_NAME(t_yield));
    lua_register(L, "t_complete_stage", GAME_LUA_BINDING_NAME(t_complete_stage));
    lua_register(L, "t_wait_for_no_danger", GAME_LUA_BINDING_NAME(t_wait_for_no_danger));
    lua_register(L, "prng_ranged_float", GAME_LUA_BINDING_NAME(prng_ranged_float));
    lua_register(L, "prng_ranged_integer", GAME_LUA_BINDING_NAME(prng_ranged_integer));
    lua_register(L, "prng_normalized_float", GAME_LUA_BINDING_NAME(prng_normalized_float));
    lua_register(L, "camera_traumatize", GAME_LUA_BINDING_NAME(camera_traumatize));
    lua_register(L, "camera_set_trauma", GAME_LUA_BINDING_NAME(camera_set_trauma));
    lua_register(L, "async_task", GAME_LUA_BINDING_NAME(async_task));
    lua_register(L, "alloc_particle_emitter", GAME_LUA_BINDING_NAME(alloc_particle_emitter));
    lua_register(L, "global_elapsed_time", GAME_LUA_BINDING_NAME(global_elapsed_time));
    lua_register(L, "ticktime", GAME_LUA_BINDING_NAME(ticktime));
    lua_register(L, "engine_dofile", GAME_LUA_BINDING_NAME(engine_dofile));
}
