// Autogenerated file. Do not touch
void bind_gameplay_dialogue_lualib(lua_State* L){
    lua_register(L, "dialogue_start", GAME_LUA_BINDING_NAME(dialogue_start));
    lua_register(L, "dialogue_end", GAME_LUA_BINDING_NAME(dialogue_end));
    lua_register(L, "dialogue_say_line", GAME_LUA_BINDING_NAME(dialogue_say_line));
    lua_register(L, "dialogue_speaker_set_visibility", GAME_LUA_BINDING_NAME(dialogue_speaker_set_visibility));
    lua_register(L, "dialogue_speaker_set_image_scale", GAME_LUA_BINDING_NAME(dialogue_speaker_set_image_scale));
    lua_register(L, "dialogue_speaker_set_image", GAME_LUA_BINDING_NAME(dialogue_speaker_set_image));
    lua_register(L, "dialogue_speaker_set_mirrored", GAME_LUA_BINDING_NAME(dialogue_speaker_set_mirrored));
    lua_register(L, "dialogue_speaker_set_position_offset", GAME_LUA_BINDING_NAME(dialogue_speaker_set_position_offset));
    lua_register(L, "dialogue_speaker_animation_fade_out", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_fade_out));
    lua_register(L, "dialogue_speaker_animation_fade_in", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_fade_in));
    lua_register(L, "dialogue_speaker_animation_slide_fade_out", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_slide_fade_out));
    lua_register(L, "dialogue_speaker_animation_slide_fade_in", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_slide_fade_in));
    lua_register(L, "dialogue_speaker_animation_jump", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_jump));
    lua_register(L, "dialogue_speaker_animation_shake", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_shake));
    lua_register(L, "dialogue_speaker_animation_focus_out", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_focus_out));
    lua_register(L, "dialogue_speaker_animation_focus_in", GAME_LUA_BINDING_NAME(dialogue_speaker_animation_focus_in));
}
