// Autogenerated file. Do not touch
void bind_v2_lualib(lua_State* L){
    lua_register(L, "v2", GAME_LUA_BINDING_NAME(v2));
    lua_register(L, "v2_add", GAME_LUA_BINDING_NAME(v2_add));
    lua_register(L, "v2_sub", GAME_LUA_BINDING_NAME(v2_sub));
    lua_register(L, "v2_dot", GAME_LUA_BINDING_NAME(v2_dot));
    lua_register(L, "v2_distance", GAME_LUA_BINDING_NAME(v2_distance));
    lua_register(L, "v2_distance_sq", GAME_LUA_BINDING_NAME(v2_distance_sq));
    lua_register(L, "v2_direction", GAME_LUA_BINDING_NAME(v2_direction));
    lua_register(L, "v2_direction_from_degree", GAME_LUA_BINDING_NAME(v2_direction_from_degree));
    lua_register(L, "v2_magnitude", GAME_LUA_BINDING_NAME(v2_magnitude));
    lua_register(L, "v2_perp", GAME_LUA_BINDING_NAME(v2_perp));
    lua_register(L, "v2_normalized", GAME_LUA_BINDING_NAME(v2_normalized));
}
